# general settings
course_number = "395676"

# Assignment specific settings
homework_dir = "hw4"
gradebook = "2025-10-03T1612_Grades-PHYS_150_500_.csv"
homework_title = "Assignment 4"
# homework_dir = "hwtest"
# gradebook = "test.csv"
# homework_title = "hwtest"

# subdirectory settings
submissions_dir = "submissionsnfeedback"
feedback_dir = "submissionsnfeedback"

# safeguard settings
timeout = 3

# feedback submission settings
debug = false
headless = false