# general settings
course_number = "395676"

# Assignment specific settings
homework_dir = "hw2"
gradebook = "2025-09-11T1927_Grades-PHYS_150_500_.csv"
homework_title = "Assignment 2"

# subdirectory settings
submissions_dir = "submissions"
feedback_dir = "feedback"

# safeguard settings
timeout = 3

# feedback submission settings
debug = true
headless = false